var aeroporti = [
'Aeroporto di Lanzarote',
'Aeroporto di Malaga',
'Aeroporto di Alicante',
'Aeroporto di Amsterdam-Schiphol',
'Aeroporto di Stoccolma-Arlanda',
'Aeroporto internazionale di Atene',
'Aeroporto internazionale di Barcellona',
'Aeroporto di Belfast',
'Aeroporto di Bergen-Flesland',
'Aeroporto di Milano-Orio al Serio',
'Aeroporto di Birmingham',
'Aeroporto di Bologna-Borgo Panigale',
'Aeroporto di Bordeaux-M‚rignac',
'Aeroporto di Bristol',
'Aeroporto di Bruxelles-Zaventem',
'Aeroporto di Basilea-Mulhouse-Friburgo',
'Aeroporto di Budapest-Ferihegy',
'Aeroporto di Parigi-Roissy',
'Aeroporto di Colonia/Bonn',
'Aeroporto di Roma-Ciampino',
'Aeroporto di Copenaghen',
'Aeroporto di Bruxelles-Charleroi',
'Aeroporto di Catania-Fontanarossa',
'Aeroporto di Mosca-Domodedovo',
'Aeroporto Internazionale di Dublino',
'Aeroporto internazionale di Dusseldorf',
'Aeroporto di Edimburgo',
'Aeroporto di Faro',
'Aeroporto di Roma-Fiumicino',
'Aeroporto di Francoforte sul Meno',
'Aeroporto di Fuerteventura',
'Aeroporto di Glasgow',
'Aeroporto di Goteborg-Landvetter',
'Aeroporto Internazionale di Ginevra',
'Aeroporto di Hannover-Langenhagen',
'Aeroporto di Amburgo-Fuhlsbuttel',
'Aeroporto di Helsinki-Vantaa',
'Aeroporto Internazionale di Heraklion',
'Aeroporto di Ibiza',
'Aeroporto di Istanbul-Ataturk',
'Aeroporto Internazionale di Boryspil',
'Aeroporto di Larnaca',
'Aeroporto di San Pietroburgo-Pulkovo',
'Aeroporto di Londra-Gatwick',
'Aeroporto di Londra Heathrow',
'Aeroporto di Milano-Linate',
'Aeroporto di Lisbona-Portela',
'Aeroporto Internazionale Gran Canaria',
'Aeroporto di Londra-Luton',
'Aeroporto di Lione-Saint',
'Aeroporto di Madrid-Barajas',
'Aeroporto di Manchester',
'Aeroporto di Malta',
'Aeroporto di Marsiglia-Provence',
'Aeroporto di Monaco di Baviera',
'Aeroporto di Milano-Malpensa',
'Aeroporto di Napoli-Capodichino',
'Aeroporto di Nizza',
'Aeroporto di Porto',
'Aeroporto di Parigi-Orly',
'Aeroporto di Oslo-Gardermoen',
'Aeroporto Internazionale Henri Coand',
'Aeroporto di Palma di Maiorca',
'Aeroporto di Palermo-Punta Raisi',
'Aeroporto di Praga-Ruzyn',
'Aeroporto di Pisa-San Giusto',
'Aeroporto di Rodi-Diagoras',
'Aeroporto Internazionale di Riga',
'Aeroporto internazionale di Salonicco',
'Aeroporto di Londra-Stansted',
'Aeroporto Internazionale di Stoccarda',
'Aeroporto di Mosca',
'Aeroporto di Berlino-Schoenefeld',
'Aeroporto di Tenerife Sur',
'Aeroporto di Toulouse-Blagnac',
'Aeroporto di Berlino-Tegel',
'Aeroporto di Venezia-Tessera',
'Aeroporto di Vienna',
'Aeroporto di Mosca-Vnukovo',
'Aeroporto di Valencia',
'Aeroporto di Varsavia',
'Aeroporto di Zurigo-Kloten'
]